// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpAqTFBpxDR5B7qXA9WsBL4KNYR3YCKoQ',
    appId: '1:203033572012:web:26154b8349b1baced7a509',
    messagingSenderId: '203033572012',
    projectId: 'race-track-66247',
    authDomain: 'race-track-66247.firebaseapp.com',
    storageBucket: 'race-track-66247.appspot.com',
    measurementId: 'G-2319RY1BMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsNL8iSXXb5gPBum4ZPufR6bqdS6ZaZfQ',
    appId: '1:203033572012:android:ed0011ea66bda429d7a509',
    messagingSenderId: '203033572012',
    projectId: 'race-track-66247',
    storageBucket: 'race-track-66247.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuly4djGzRyR-5u6rI1GaqyOsPSWfvg3M',
    appId: '1:203033572012:ios:14cb10f5670d9cbcd7a509',
    messagingSenderId: '203033572012',
    projectId: 'race-track-66247',
    storageBucket: 'race-track-66247.appspot.com',
    iosBundleId: 'com.example.loginrace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuly4djGzRyR-5u6rI1GaqyOsPSWfvg3M',
    appId: '1:203033572012:ios:c34f729d0afab151d7a509',
    messagingSenderId: '203033572012',
    projectId: 'race-track-66247',
    storageBucket: 'race-track-66247.appspot.com',
    iosBundleId: 'com.example.loginrace.RunnerTests',
  );
}
